---
title: "KALD2 map for pH ms"
author: "Christina Bonsell"
date: "2 Sept 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F, message=F, warnings=F}
library(leaflet)
library(tidyverse)
```

```{r load,echo=F, message=F, warnings=F}
Stations <- read_csv("BLE_LTER_CP_Stations.csv", 
                     col_types=cols(
  StationId = col_character(),
  StationName = col_character(),
  Latitude = col_double(),
  Longitude = col_double(),
  Habitat = col_character(),
  Type = col_factor()
)) %>% 
  filter(StationId=="KALD2") %>% 
  mutate(LabName="Kaktovik Lagoon")

```

#SQUARE

## Zoom out and screenshot
```{r zoom, echo=F, message=F, warnings=F, fig.height=6, fig.width=6}

Stations %>% leaflet() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>% 
  addCircleMarkers(~ Longitude, ~ Latitude, 
                   color = "white",
                   radius=4,
                   stroke = FALSE, 
                   fillOpacity = 0.5,
                   label= ~LabName,
                   labelOptions = labelOptions(noHide = T,
                                               direction = 'right',
                                               offset=c(0,0),
                                               opacity=1,
                                               style = list(
                                                 "font-style" = "bold",
                                                 "font-size" = "14px",
                                                 "color"="white",
                                                 "background"="transparent",
                                                 "border"="none",
                                                 "box-shadow"="none"))) %>% 
  addScaleBar() %>% 
  addMiniMap(zoomLevelFixed = 2, 
             centerFixed=c(65, -150))


```

## Hidden labels
```{r nolab, echo=F, message=F, warnings=F, fig.height=6, fig.width=6}

Stations %>% leaflet() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>% 
  addCircleMarkers(~ Longitude, ~ Latitude, 
                   color = "white",
                   radius=4,
                   stroke = FALSE, 
                   fillOpacity = 1,
                   label= ~LabName) %>% 
  addScaleBar() %>% 
  addMiniMap(zoomLevelFixed = 2, 
             centerFixed=c(65, -150))


```

#WIDE

## Zoom out and screenshot
```{r wide, echo=F, message=F, warnings=F, fig.width=11}

Stations %>% leaflet() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>% 
  addCircleMarkers(~ Longitude, ~ Latitude, 
                   color = "white",
                   radius=4,
                   stroke = FALSE, 
                   fillOpacity = 0.5,
                   label= ~LabName,
                   labelOptions = labelOptions(noHide = T,
                                               direction = 'right',
                                               offset=c(0,0),
                                               opacity=1,
                                               style = list(
                                                 "font-style" = "bold",
                                                 "font-size" = "14px",
                                                 "color"="white",
                                                 "background"="transparent",
                                                 "border"="none",
                                                 "box-shadow"="none"))) %>% 
  addScaleBar() %>% 
  addMiniMap(zoomLevelFixed = 2, 
             centerFixed=c(65, -150))


```

## Hidden labels
```{r widenolab, echo=F, message=F, warnings=F,fig.width=11}

Stations %>% leaflet() %>% 
  addProviderTiles(providers$Esri.WorldImagery) %>% 
  addCircleMarkers(~ Longitude, ~ Latitude, 
                   color = "white",
                   radius=4,
                   stroke = FALSE, 
                   fillOpacity = 1,
                   label= ~LabName) %>% 
  addScaleBar() %>% 
  addMiniMap(zoomLevelFixed = 2, 
             centerFixed=c(65, -150))


```
